import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const initialValues = {
  cost: 0,
  deposit: 0,
  interest: 0,
  mortgageTerm: 0,
  serviceCharge: 0,
  groundRent: 0,
  rent: 0,
  agencyFees: 0,
  agencyFeesTax: 0,
  landlordInsurance: 0
};

export default function Home() {

  const [monthlyMortgage, setMonthlyMortgage] = useState<any>();
  const [monthlyIncome, setMonthlyIncome] = useState<number>(0);
  const [values, setValues] = useState(initialValues);
  const [showMonthlyIncome, setShowMonthlyIncome] = useState<boolean>(false);

  const handleInputChange = (e:any) => {
    const { name, value } = e.target;
    setValues({
      ...values,
      [name]: value,
    });
  };

  const calculateMonthlyMortgage = async () => {
    
    const interestRatePerMonth: number = values.interest / 100 / 12;

    const mortgage = (values.cost - values.deposit) * interestRatePerMonth * (Math.pow(1 + interestRatePerMonth, values.mortgageTerm * 12)) / (Math.pow(1 + interestRatePerMonth, values.mortgageTerm * 12) - 1);

    setMonthlyMortgage(mortgage);
    setShowMonthlyIncome(true);

  }

  const calculateMonthlyIncome = async () => {
    const agencyFees = (values.rent * values.agencyFees) / 100;
    
    const income =
      values.rent -
      (monthlyMortgage +
        values.serviceCharge / 12 +
        values.groundRent / 12 +
        values.landlordInsurance / 12 +
        agencyFees +
        (agencyFees * values.agencyFeesTax) / 100);
    
    setMonthlyIncome(income);
  }

  return (
    <>
      <Head>
        <title>Buy-To-Let Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div>
          <section className="gradient-form bg-gray-200 p-4">
            <div className="container py-1 px-3">
              <div className="flex flex-wrap g-6 text-gray-800">
                <div className="">
                  <div className="block bg-white shadow-lg rounded-lg">
                    <div className="lg:flex lg:flex-wrap g-0">
                      <div className="px-4 md:px-0">
                        <div className="md:p-12 md:mx-6">
                          <div className="text-center">
                            <h4 className="text-xl font-semibold mt-1 mb-4 pb-1 pt-4">
                              Buy-To-Let Calculator
                            </h4>
                            <hr className="pb-4" />
                          </div>
                          <p className="mb-4">
                            Enter various expenses to calculate profit on
                            buy-to-let properties
                          </p>
                          <div className="mb-4">
                            <label
                              htmlFor="cost"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Cost of property
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Cost of the property"
                              name="cost"
                              value={values.cost}
                              onChange={handleInputChange}
                            />
                          </div>
                          <div className="mb-4">
                            <label
                              htmlFor="deposit"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Deposit Amount
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Deposit"
                              name="deposit"
                              value={values.deposit}
                              onChange={handleInputChange}
                            />
                          </div>
                          <div className="mb-4">
                            <label
                              htmlFor="interest"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Mortgage interest (%){" "}
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Mortgage interest"
                              name="interest"
                              value={values.interest}
                              onChange={handleInputChange}
                            />
                          </div>
                          <div className="mb-4">
                            <label
                              htmlFor="mortgageTerm"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Mortgage Length (in Years)
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Mortgage Length (in Years)"
                              name="mortgageTerm"
                              value={values.mortgageTerm}
                              onChange={handleInputChange}
                            />
                          </div>

                          <div className="mb-4">
                            <button
                              type="button"
                              className="form-control block w-full bg-white bg-clip-padding border-solid  rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none px-6 py-2 border-2 border-green-600 text-green-600 font-medium text-xs leading-tight uppercase hover:bg-black hover:bg-opacity-5 focus:ring-0 duration-150
                              "
                              onClick={calculateMonthlyMortgage}
                            >
                              Calculate Monthly Mortgage
                            </button>
                          </div>

                          {monthlyMortgage > 0 && (
                            <div
                              className="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4"
                              role="alert"
                            >
                              <p className="font-bold">
                                Monthly mortage with a deposit of {Math.round((values.deposit / values.cost) * 100)}% will be
                                £{parseInt(monthlyMortgage)}
                              </p>
                              {/* <p></p> */}
                            </div>
                          )}

                          {/*
                           ******************************** Show Monthly Mortgage ***********************************
                           */}

                          <div className="mb-4">
                            <label
                              htmlFor="serviceCharge"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Service Charge (Yearly)
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Service Charge"
                              name="serviceCharge"
                              value={values.serviceCharge}
                              onChange={handleInputChange}
                            />
                          </div>

                          <div className="mb-4">
                            <label
                              htmlFor="groundRent"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Ground Rent (Yearly)
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Ground Rent"
                              name="groundRent"
                              value={values.groundRent}
                              onChange={handleInputChange}
                            />
                          </div>

                          <div className="mb-4">
                            <label
                              htmlFor="rent"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Monthly Rent
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Rent"
                              name="rent"
                              value={values.rent}
                              onChange={handleInputChange}
                            />
                          </div>

                          <div className="mb-4">
                            <label
                              htmlFor="agencyFees"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Agency Fees (%)
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Agency Fees (in %)"
                              name="agencyFees"
                              value={values.agencyFees}
                              onChange={handleInputChange}
                            />
                          </div>

                          <div className="mb-4">
                            <label
                              htmlFor="agencyFeesTax"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Agency Fees VAT/Tax (%)
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Agency Fees (in %)"
                              name="agencyFeesTax"
                              value={values.agencyFeesTax}
                              onChange={handleInputChange}
                            />
                          </div>

                          <div className="mb-4">
                            <label
                              htmlFor="landlordInsurance"
                              className="form-label inline-block mb-2 text-gray-700 font-bold"
                            >
                              Landlord Insurance (Yearly)
                            </label>
                            <input
                              type="text"
                              className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                              placeholder="Agency Fees (in %)"
                              name="landlordInsurance"
                              value={values.landlordInsurance}
                              onChange={handleInputChange}
                            />
                          </div>

                          <div className="text-center pt-1 mb-12 pb-1">
                            <button
                              type="button"
                              className="inline-block px-6 py-2 border-2 border-green-600 text-green-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out float-right w-full"
                              onClick={calculateMonthlyIncome}
                            >
                              Calculate Monthly Income
                            </button>
                          </div>

                          {showMonthlyIncome && (
                            <div
                              className="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4"
                              role="alert"
                            >
                              <p className="font-bold">
                                <ul>
                                  <li>Service Charge: {Math.round(values.serviceCharge / 12)}</li>
                                  <li>Ground Rent: {Math.round(values.groundRent / 12)}</li>
                                  <li>Landlord Insurance: {Math.round(values.landlordInsurance / 12)}</li>
                                  <li>Agency Fees: {Math.round((values.rent * values.agencyFees) / 100)}</li>
                                  <li>Agency Fees Tax: {Math.round((((values.rent * values.agencyFees) / 100) * values.agencyFeesTax) / 100)}</li>
                                </ul>
                                <hr />
                                Monthly Income: £
                                {Math.round(monthlyIncome)}
                              </p>
                              {/* <p></p> */}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
